### PR TITLE
Fix types

### LINKED ISSUE #2: Improve TypeScript types
The class should be identical to `Map`, except that it requires an array as key. Currently the types are exactly those of `Map`

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #2 
- Closes #10

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1 +1,6 @@
-export default class ManyKeysMap<K, V> extends Map<K[], V> {}
+export default class ManyKeysMap<K extends readonly unknown[], V> extends Map<K, V> {
```
Comment (fregante) [inline index.d.ts:1]: @mshriner I think this is the right way to enforce tuples here.

I'm not publishing this yet, I can accept a PR with further tests now that the whole testing suite is in TS
